#配置注册中心1的端口，可以随意设置，不能跟其他端口冲突
server:
  port: 10010
#配置注册中心1的名字，可以随意起
spring:
  application:
    #通过查看注册中心查看有哪些模块注册进了这个注册中心
    name: hbuy-eureka
eureka:
  instance:
#    hostname: 127.0.0.1
    hostname: localhost
  client:
    # 是否向eureka注册自身服务
    register-with-eureka: false
    #是否检索服务
    fetch-registry: false
    #服务注册地址
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://${eureka.instance.hostname}:10010/eureka/
      defaultZone: http://localhost:10010/eurekaaaaaaa
#      defaultZone: http://127.0.0.1:10010/eureka/